### ISSUE TITLE
Function calls are not supported after install

### ISSUE THREAD

**Issue by Zelosien** [leewinder/ng2-file-drop#11] opened 2017-03-04 20:29 UTC
Hi, i follow the example here : 
-> https://github.com/leewinder/ng2-file-drop/tree/master/samples/src/app/components/file-drop-samples/image-validation

But : 
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in C:/Users/Zelo/Ide
aProjects/GLHF/Client/node_modules/ng2-file-drop/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in C:/Users/Zelo/IdeaProjects/GLHF/Client/node_modules/ng2-file-drop/node_modules/@angular/core/src/metadata.d.ts, resolving symbo
l NgModule in C:/Users/Zelo/IdeaProjects/GLHF/Client/node_modules/ng2-file-drop/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in C:/Users/Zelo/IdeaProjects/GLHF/Client/node_modules/ng2-file-drop/node_modules/@angular/core/index.d.ts, resol
ving symbol FileDropModule in C:/Users/Zelo/IdeaProjects/GLHF/Client/node_modules/ng2-file-drop/module/file-drop.module.ts, resolving symbol FileDropModule in C:/Users/Zelo/IdeaProjects/GLHF/Client/node_modules/ng2-file-drop/module/file-drop.module.ts

Help pls :s

app.module : 
import { Ng2FileDropModule }  from 'ng2-file-drop';
...
imports: [ ... NgProgressModule, ... ]
...

package.json :

"devDependencies": {
    "@angular/cli": "^1.0.0-rc.1",
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular2-swiper-wrapper": "^2.2.3",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "jquery": "^3.1.1",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }

**Comment by rajeshbaburocz** [comment] 2017-04-03 11:01
Probably related to #8

**Comment by leewinder** [comment] 2017-06-10 20:46
Duplicate of #8

**Closed by leewinder** 2017-06-10 20:46 UTC
